### ISSUE TITLE
Need Text file integration with the Quiz Python program. 

### ISSUE THREAD

**Issue by SoumyajitNag18** [ItsKinggpinn/Hacktoberfest-2022#1]
Need **two different text files integration with the Quiz python program**, _one for the quiz questions_ and _another for the respective answers_.
(In this program we are actually giving the questions and answer in the program. But, we need certain changes like the questions and it's respective answers are provided in different text documents and the Quiz python file is accessing them!)

**Comment by kingpin-ay** [comment]
I am interested In solving this problem . if you can give me the agree status I will start from Tomorrow.

**Comment by SoumyajitNag18** [comment]
Thanks for the contribution @kingpin-ay . The issue is finally solved..
