### ISSUE TITLE
FCFS(First come first serve algorithm) with User defined numbers)

### ISSUE THREAD

**Issue by SoumyajitNag18** [ItsKinggpinn/Hacktoberfest-2022#12]
**_Problem:_**
Make a program that implements **FCFS Algorithm with user defined data** with user defined data limit. Calculate the **_average waiting time and average turn around time_**.

**Comment by AdarshaHalder** [comment]
can you assign this issue to me

**Comment by SoumyajitNag18** [comment]
Yes , I'm assigning you .

**Comment by Premjeet1804** [comment]
can you assign something to me

**Comment by AdarshaHalder** [comment]
I  solved your problem. kindly check please

**Comment by SoumyajitNag18** [comment]
Thank @AdarshaHalder for helping and solving out the problem.
