### ISSUE TITLE
Stopwatch program with start, pause & stop button

### ISSUE THREAD

**Issue by SoumyajitNag18** [ItsKinggpinn/Hacktoberfest-2022#17]
Write a program to make a small code for Stopwatch with start, pause and stop buttons.

**Comment by AdarshaHalder** [comment]
hello can you assign to me

**Comment by SoumyajitNag18** [comment]
Sure, just a moment.

**Comment by AdarshaHalder** [comment]
thank you

**Comment by AdarshaHalder** [comment]
done please check it sir
