### ISSUE TITLE
GUI for the main page of a website

### ISSUE THREAD

**Issue by SoumyajitNag18** [ItsKinggpinn/Hacktoberfest-2022#19]
Create a **_graphical user interface for the main page of the website_** which will contain some basic information about anyone or anything.

**Comment by swarnajha** [comment]
Assign me this issue please.

**Comment by SoumyajitNag18** [comment]
Okayy, just wait a min and I'll assign you.

**Comment by swarnajha** [comment]
I have solved it, can you check it once.

**Comment by SoumyajitNag18** [comment]
Yes, I'm checking.
