### ISSUE TITLE
Hand Cricket Program with USER vs AI(randomly generated)

### ISSUE THREAD

**Issue by SoumyajitNag18** [ItsKinggpinn/Hacktoberfest-2022#2]
_**Problem:-**_

- We want to make a _Hand Cricket Program consisting of a player(user) & AI(random number generator)_. 
- It consists of two parts where there is a **run "counter"**(starting from 0) and a **"wicket" flag**(0 or false when there is 0 wickets on score board whereas 1 or True when there wickets fall and innings end for him). There is only one wicket for the both the sides in each innings. 
- Toss round will have either 1 or 0 by the player. If the player's guess matches with that of the random function producing 0 or 1, then he wins the toss otherwise he loses.(1 or 1 / 0 or 0 - toss won else 0 or 1 / 1 or 0 - toss lost )
- After winning the toss, player can take the character 'b' for batting or 'f' for fielding. In case of AI, 'b and 'f' will be randomized.
- Player and AI can only have numbers from 0 to 10.

_**Input;-**_
1.  **Case 1**: Player (bat) --> <num==6> vs AI(bowl)--> <num!=6> : Player hits a sixer.
2. **Case 2**: Player (bat) --> <num==6> vs AI(bowl)--> <num==6> : AI end the innings of player with wicket.
...and so on with that of Player (bowl) vs AI(bat).

**_Output;-_**
1. **Case 1**: Player (2nd batting, **winners**) vs  AI(bowl): <Run chasing> Player wins, AI loses.
2. **Case 2**: AI(2nd batting, **winners**) vs  Player(bowl): <Run chasing> AI wins, Player loses.

Note: 
1. Any coding language preferably Java or Python 3.
2. Bots can also win toss(≡when Player is losing the toss).

**Comment by kingpin-ay** [comment]
I did like to contribute on this problem **can you assign this problem to me**  and thank you

**Comment by SoumyajitNag18** [comment]
Alright I'm assigning.
