### ISSUE TITLE
Basic Matrix operation

### ISSUE THREAD

**Issue by SoumyajitNag18** [ItsKinggpinn/Hacktoberfest-2022#20]
**_Problem;-_** 
Take two 'n x n' matrices where 'n' is the order of the matrix from user defined input. 
Matrix order and elements of the matrices needs to USER DEFINED.
Then perform matrix multiplication between them.

**Comment by TheHappyBaloney** [comment]
Hi, 
Kindly assign this issue to me.
Thanks.

**Comment by SoumyajitNag18** [comment]
Sure. You are good to go with this . @Arunima-Chatterjee

**Comment by aryanh0911** [comment]
which language is to be used?

**Comment by SoumyajitNag18** [comment]
Any language can be used !
