### ISSUE TITLE
Greedy algorithm

### ISSUE THREAD

**Issue by SoumyajitNag18** [ItsKinggpinn/Hacktoberfest-2022#26]
A frog is jumping up a staircase with n steps and can hop either 1 step, 2 steps, or 3 steps at a time. Implement a method to count how many possible ways the frog can jumping  up the stairs.

**Comment by AdarshaHalder** [comment]
hello ............i want to solve this.............can you assign me please sir..i already solved your many problem already

**Comment by SoumyajitNag18** [comment]
Yeah. I hope you might solve and contribute to the open source with this one as well!

**Comment by AdarshaHalder** [comment]
yes sir please assign me it

**Comment by AdarshaHalder** [comment]
thank you

**Comment by ankit060801** [comment]
hello sir! please assign me this task

**Comment by AdarshaHalder** [comment]
i added it.merge it please

**Comment by SoumyajitNag18** [comment]
Sorry the issue has been solved. Thanks for the contribution .
