### ISSUE TITLE
Pattern program

### ISSUE THREAD

**Issue by SoumyajitNag18** [ItsKinggpinn/Hacktoberfest-2022#32]
1
12
123
1234
12345
1234
123
12
1

Write a code to print this pattern using loop statement.

**Comment by AnirudhJalan** [comment]
please can u assign me this

**Comment by SoumyajitNag18** [comment]
ok, I'm assigning!

**Comment by ankit060801** [comment]
pls assign to do this task

**Comment by s4shantanu** [comment]
Can i contribute on this issue

**Comment by Deepanshu1008** [comment]
Can you assign me this issue?

**Comment by Git-Akshat01** [comment]
Hi! @ItsKinggpinn Can you please assign me this task?
