### ISSUE TITLE
Spy_Duck check

### ISSUE THREAD

**Issue by SoumyajitNag18** [ItsKinggpinn/Hacktoberfest-2022#34]
**_Problem:-_**
Write a program that takes user defined number to check whether it's a duck number or not OR it's a spy number or not!

**_Inputs:-_**
1.  User defined menu for Spy or Duck Number checking.
2. User defined number for the checking.

**Comment by Moumita-08** [comment]
I want to solve it. Pls assign me.

**Comment by SoumyajitNag18** [comment]
Okay, go for it and complete it!
