### ISSUE TITLE
Infix to Postfix Conversion using stack

### ISSUE THREAD

**Issue by SoumyajitNag18** [ItsKinggpinn/Hacktoberfest-2022#38]
Explain **_Infix to Postfix Conversion using stack_**.
Note: No coding contributions is allowed as well.

**Comment by srijan32002** [comment]
Can i contribute?

**Comment by SoumyajitNag18** [comment]
Yes go for it ! @itz-cyber19

**Comment by srijan32002** [comment]
Thanks!
