### ISSUE TITLE
Merge two different Linked Lists

### ISSUE THREAD

**Issue by SoumyajitNag18** [ItsKinggpinn/Hacktoberfest-2022#42]
Write a program to  **_merge two different linked lists_**.

**Comment by ghost** [comment]
Please give me responsibility for this problem.

**Comment by SoumyajitNag18** [comment]
I'm giving you!

**Comment by apoorvajagtap** [comment]
Hey @ItsKinggpinn, can I also work on this one? I'll prefer to solve this problem using GoLang. Let me know, if there are any language limitations.

**Comment by saishubham468** [comment]
Hi @ItsKinggpinn can you assign me this issue i have the code ready to solve the issue.
