### ISSUE TITLE
Check Fibonacci series Element

### ISSUE THREAD

**Issue by SoumyajitNag18** [ItsKinggpinn/Hacktoberfest-2022#44]
**_Problem:-_**
Write a program that takes user defined number to check whether it is available in the Fibonacci Series or not.

 **_Input:-_**
Enter a number to be checked: 13

**_Output:-_**
13 is available in Fibonacci series.

**Comment by vaibhv232** [comment]
hello sir, assign it to me

**Comment by srijan32002** [comment]
Can i contribute?

**Comment by SoumyajitNag18** [comment]
Yes you can! @itz-cyber19

**Comment by saishubham468** [comment]
Hi @ItsKinggpinn can i contribute to this code and in which language do you need the code for.
