### ISSUE TITLE
Scatter Plotting Problem

### ISSUE THREAD

**Issue by SoumyajitNag18** [ItsKinggpinn/Hacktoberfest-2022#46]
Provided a sales data of each month and show it using a scatter plot. I am facing problem doing it in python actually I have a data but I am unable to plot it.

**Comment by kingpin-ay** [comment]
hello it's kingpin-ay again
can you assign this problem to me .?

**Comment by SoumyajitNag18** [comment]
Surely. I'm assigning it!

**Comment by Saloni2004** [comment]
Hey, please assign me this
