### ISSUE TITLE
Want a new login menu "Form" design for the community.

### ISSUE THREAD

**Issue by SoumyajitNag18** [ItsKinggpinn/Hacktoberfest-2022#7]
**_Problem:_**
I want help in making a form(using any frontend tools like HTML 5, CSS, Javascript, etc) for the frontend of my community's website with color accents focusing on #0086b3 ,#007399 , #4dd2ff , White fonts inside the Submit button for Login menu .

**_Input:-_**
Any Frontend tools - HTML 5, CSS & Javascript (preferred)

**_Output:-_**
Updated new looks for the Login Form of the community.

**Comment by Yushmanth-reddy** [comment]
hey could you assign we this. also could you please specify the work that needs to be done as I am new to open source.

**Comment by Yushmanth-reddy** [comment]
could you assign me this. also could you please specify the work that needs to be done as I am new to open source.

**Comment by SoumyajitNag18** [comment]
Surely, actually I want a **_just the form design_** (a new one with some colour themes mentioned in hex codes) . If you can make the form format it'll be helpful for me and my community and even the open source contribution in a noble job as well!

Examples - BY FORMS, I mean 
https://profile.w3schools.com/log-in?redirect_url=https%3A%2F%2Fmy-learning.w3schools.com

**Comment by Yushmanth-reddy** [comment]
should I add any images or just plain form with design works?

**Comment by SoumyajitNag18** [comment]
Well you are good to go with customization as per your choice and it's recommended to go for design works with the color themes as I mentioned in the form of Hex codes.

**Comment by aryanh0911** [comment]
new to opensource here. Could you specify the work you require me to do?

**Comment by SoumyajitNag18** [comment]
Well @aryanh0911 you'll just have to make the front end FORM FOR LOGIN of a website with any tool .
